# Validation definiton for container wpnd cli will generate
# using container-structure-test (https://github.com/GoogleContainerTools/container-structure-test)

schemaVersion: 2.0.0

commandTests:
  - name: "Composer is bundled with image"
    command: "which"
    args: ["composer"]
    expectedOutput: ["/usr/bin/composer"]

metadataTest:
  cmd: ["apache2-foreground"]
  entrypoint: ["entrypoint-child.sh"]
