name: code-health-check

on: [push]

jobs:
  code-health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '14.x'
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Unit Test
        run: yarn test:unit

  verify-container:
    needs: code-health-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '14.x'
      - name: Install Container Structure Test Binary
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 \
          && chmod +x container-structure-test-linux-amd64 \
          && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin \
          && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build and start image
        working-directory: playground
        run: yarn start
      - name: Test Generated Container
        run: yarn test:container
      - name: Teardown created container
        working-directory: playground
        run: yarn destory
