name: code-health-check

on: [push]

jobs:
  code-health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '18.x'
      - name: Install Project Dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Unit Test
        run: yarn workspace wpnd test:unit

  verify-container:
    needs: code-health-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '18.x'
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Container Structure Test Binary
        run: >
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          && chmod +x container-structure-test-linux-amd64
          && mkdir -p $HOME/.local/bin
          && mv container-structure-test-linux-amd64 $HOME/.local/bin/container-structure-test
          && echo "$HOME/.local/bin/container-structure-test" >> $GITHUB_PATH
      - name: Install Project Dependencies
        run: yarn install --immutable
      - name: Build and start image
        run: yarn playground:start -d
      - name: Test Generated Container
        run: yarn test:container
      - name: Teardown created container
        run: yarn playground:destroy
