name: integration-quality-check

on:
  workflow_run:
    workflows: ['code-health-check']
    types: [completed]

jobs:
  on-code-check-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '14.x'
      - name:
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 \
          && chmod +x container-structure-test-linux-amd64 \
          && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin \
          && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build and Start Image
        working_directory: ./playground
        run: yarn start
      - name: Test container
        run: container-structure-test test --config config-cst.yaml --image random808443
      - name: Destroy Container
        working_directory: ./playground
        run: yarn destroy

  on-code-check-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'triggering integration workflow failed'
