name: publish package

on:
  workflow_run:
    workflows: ['integration-quality-check']
    branches: ['main']
    types:
      - completed

jobs:
  on-integration-quality-check-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '14.x'
      - name: Install dependencies and build 🔧
        run: yarn install --immutable
      - name: Install semantic-release extra plugins
        run: yarn add @semantic-release/changelog @semantic-release/git --dev
#      - name: Build
#        run: yarn build
      - name: Release
        run: yarn dlx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  on-integration-quality-check-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering package publish workflow failed'
