name: publish package

on:
  workflow_run:
    workflows: ['code-health-check']
    branches: ['main']
    types:
      - completed

jobs:
  on-code-check-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '22.x'
      - name: Install dependencies and build 🔧
        run: yarn install --immutable
      - name: Install semantic-release extra plugins
        run: yarn add @semantic-release/changelog@6.0.3 @semantic-release/git@10.0.1 --dev
      - name: Release
        working-directory: module
        run: yarn dlx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  on-code-check-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'code health check workflow failed'
